---
- name: "Check if cargo is installed"
  shell: command -v cargo
  register: cargo_exists
  
- name: "Install cargo packages"
  community.general.cargo:
    name: "{{ item }}"
    state: latest
  when: cargo_exists is success
  loop: 
    - pwninit