---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection" }
    - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/SecLists" }
    - { repo: "https://github.com/carlospolop/PEASS-ng", location: "/opt/PEASS"}
    - { repo: "https://github.com/fortra/impacket", location: "/opt/impacket"}
    - { repo: "https://github.com/byt3bl33d3r/CrackMapExec", location: "/opt/CrackMapExec"}
  become: true
  become_method: sudo

- name: "Installing impacket"
  pip:
    name: .
    chdir: /opt/impacket
  become: true
  become_method: sudo

- name: "Installing CrackMapExec"
  pip:
    name: .
    chdir: /opt/CrackMapExec
  become: true
  become_method: sudo