---
- include_tasks: apt-tools.yml
- include_tasks: gdb-plugins.yml
- include_tasks: cargo-tools.yml
- include_tasks: pip-tools.yml
- include_tasks: gem-tools.yml
- include_tasks: go-tools.yml
- include_tasks: ghidra.yml
- include_tasks: github-repos.yml
- include_tasks: pipx-tools.yml